version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_PWD=your_password
    ports:
      - "1521:1521"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - oracle-data:/opt/oracle/oradata

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - ./minio/data:/data

  auth-service:
    build:
      context: ./backend/auth-service
    ports:
      - "8000:8000"
    depends_on:
      - oracle-db

  video-service:
    build:
      context: ./backend/video-service
    ports:
      - "8001:8001"
    depends_on:
      - oracle-db
      - minio

  storage-service:
    build:
      context: ./backend/storage-service
    ports:
      - "8002:8002"
    depends_on:
      - minio

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - video-service
      - storage-service

volumes:
  oracle-data: